basePath: /
definitions:
  Server:
    properties:
      city: {type: string}
      provider: {type: string}
      public_ip: {type: string}
      state: {type: string}
      zip_code: {type: string}
    type: object
host: AUTO:6003
info:
  contact: {email: nakamoto@nakamoto.com, name: Satoshi Nakamoto}
  description: Run a traceroute on demand for bitcoin.
  title: Bitroute
  x-21-category: utilities
  x-21-github-project-url: https://github.com/21dotco/bitroute
  x-21-keywords: [traceroute, network]
  x-21-quick-buy: '21 buy "http://AUTO:6003/traceroute21?uri=21.co"'
  x-21-total-price: {max: 1000, min: 1000}
paths:
  /:
    get:
      consumes: [application/x-www-form-urlencoded]
      produces: [application/json]
      responses:
        200:
          description: Traceroute statistics and information on server location.
          schema:
            properties:
              ping:
                items: {type: string}
                type: array
              server: {$ref: '#/definitions/Server'}
            type: object
      summary: Return traceroute statistics between this device and a given domain
        or IP.
schemes: [http]
swagger: '2.0'
x-21-manifest-path: /manifest
